baseURL = "https://web-personal-dieja.vercel.app/"
locale = 'en-us'
title = 'Dieja'
theme = "PaperMod"
relativeURLs = true

[params]
mainSections = ["posts"]
ShowPostNavLinks = true

[params.profileMode]
enabled = false

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "Selamat datang di catatan perjalananku."

[[params.socialIcons]]
name = "github"
url = "https://github.com/rezahrdnto"

[[menu.main]]
name = "Playlist"
url = "/categories/"
weight = 10