baseURL = "https://web-personal-dieja.vercel.app/"
languageCode = "en-us"
title = "Dieja"
theme = "PaperMod"

[params]
defaultTheme = "auto"
mainSections = ["posts"]
ShowPostNavLinks = true
ShowBreadCrumbs = true
hideFooter = true
ShowPostCategories = true
ShowPostDescription = true

[params.profileMode]
enabled = false

[params.homeInfoParams]
Title = "Halo"
Content = "Tulisan pendek."

[[params.socialIcons]]
name = "github"
url = "https://github.com/rezahrdnto"

[[menu.main]]
name = "Playlist"
url = "/categories/"
weight = 10