baseURL = "https://web-personal-dieja.vercel.app/"
locale = 'en-us'
title = 'Dieja Pertama'
theme = "PaperMod"
relativeURLs = true

[params]
mainSections = ["posts"]

[params.profileMode]
enabled = false

[[params.socialIcons]]
name = "github"
url = "https://github.com/rezahrdnto"